#ifndef EVENT_RECEIVER_ID_H
#define EVENT_RECEIVER_ID_H

#define RECEIVER_ID_INVALID         0
#define RECEIVER_ID_ENGINE          1
#define RECEIVER_ID_EVENT_LOGGER    2
#define RECEIVER_ID_CACHE_ORDERS    3

#endif